version: '3.8'
services:
  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"
    environment:
      - MONGO_INITDB_DATABASE=air_quality_db
    volumes:
      - ./data/db:/opt/data/db


  # db:
  #   image: postgres:11.4-alpine
  #   #restart: always
  #   environment:
  #     POSTGRES_USER: slickuser
  #     POSTGRES_PASSWORD: slickpass
  #     POSTGRES_DB: air_quality_db
  #   ports:
  #     - 5432:5432
      
  # adminer:
  #   image: adminer
  #   #restart: always
  #   ports:
  #     - 8080:8080
 
  app:
    image: air_quality-app
    build: .
    ports:
      - 5052:5052
    environment:
      DB_HOST: 'mongodb://mongo:27017/air_quality_db'
      IQAIR_API_KEY: 45b05d0d-c3be-45a5-aced-44a72cd3ba24
    depends_on:
      - mongo

