name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  test_build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Lint and test
        run: npm run lint && npm run test && npm run build && npm run coverage

      - name: Check circular dependencies
        run: npx madge --circular --extensions ts src

  deploy:
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: npm run build && docker build -t your-docker-image .

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: |
          docker tag your-docker-image:latest your-docker-username/your-docker-repo:latest
          docker push your-docker-username/your-docker-repo:latest
