name: CI/CD - PrePush to Master

on:
  push:
    branches:
      - master

jobs:
  Test_Build:
    runs-on: ubuntu-latest

    services:
        mongodb:
          image: mongo
          ports:
            - 27017:27017
          env:
            MONGO_INITDB_DATABASE: air_quality_db_test       
          options: >-
            --health-cmd "mongo --eval printjson(db.stats())" --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install
      
      # - name: Run Lint
      #   run: npm run lint

      - name: Build Code
        run: npm run compile
      
      - name: Run Tests 
        run: npm run test
  
  deploy:
    runs-on: ubuntu-latest
    needs: test_build
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: Docker build -t air-quality-app .

      - name: Log in to Docker Hub
        run: echo registered 

      - name: Push Docker image
        run: echo done                      
